version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - APP_ENV=development

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development